### ISSUE TITLE
className did not match

### ISSUE THREAD

**Issue by webdevcody** [fuma-nama/fumadocs#370] opened 2024-05-15 14:41 UTC
### To Reproduce

This can be reproduced by cloning https://github.com/fuma-nama/next-docs-ui-template and running it.  I'm also seeing this same warning when setting up Fuma on my own project and loading my docs.

### The Fuma Template

<img width="1440" alt="Screenshot 2024-05-15 at 10 38 16 AM" src="https://github.com/fuma-nama/fumadocs/assets/123222405/406ff548-8549-4fc1-b1c3-978433f355d9">

### My Own Project

<img width="1439" alt="Screenshot 2024-05-15 at 10 39 57 AM" src="https://github.com/fuma-nama/fumadocs/assets/123222405/e9b42c59-240c-4582-970e-b4f25bebd3b2">

seems like it's coming from an icon?  I don't use lucide-search anywhere in my project.

### Current vs. Expected behavior

I wouldn't expect warnings

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
Binaries:
  Node: 18.17.0
  npm: 10.5.0
  Yarn: 1.22.19
  pnpm: 8.6.2
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

UI, MDX

**Comment by fuma-nama** [comment] 2024-05-16 08:34
I noticed you are cloning `next-docs-ui-template`, It was the previous name of fumadocs and have already deprecated few months ago. 
You can clone `https://github.com/fuma-nama/fumadocs-ui-template.git` instead, which is the template our CodeSandbox demo using.

I cannot reproduce the SVG hydration warning problem on my Macbook, I need to take a look at your lock file to do further investigation. You can try cloning the new template first, perhaps it can be solved.

**Comment by ahaubenstock** [comment] 2024-05-28 12:23
I am following the getting started guide at https://fumadocs.vercel.app/docs/ui, and I get that same lucide-react error on the same SVG for the default template. It does appear to be a problem in lucide-react, but then it would make sense to downgrade the fumadocs dependency on the package to a version that works.

**Comment by fuma-nama** [comment] 2024-05-28 12:40
That's odd, Fumadocs upgrades dependencies regularly and the current version of fumadocs is using the latest release of `lucide-react`. It doesn't cause problems on [CodeSandbox](https://githubbox.com/fuma-nama/fumadocs-ui-template).

The default template doesn't include a lock file so that you can bring your own package manager. It also makes our release workflow faster by not generating a lock file. Hence, I might need a reproducible repository to have a deeper look into the problem.

**Comment by fuma-nama** [comment] 2024-05-28 12:46
This is what I'm getting from a new app generated with `create-fumadocs-app`, you can see except the warning from `next-themes` aforementioned, there's no warning about SVG.
![image](https://github.com/fuma-nama/fumadocs/assets/76240755/c683e3cd-669d-442b-885b-bdad43692a16)

**Comment by ahaubenstock** [comment] 2024-05-29 06:09
It's interesting that you do not get the same SVG error. I believe it is related to the same bug in lucide-react that is referenced by this issue in their [repository](https://github.com/lucide-icons/lucide/issues/2137)

And the nav UI uses the search icon from lucide-react [here](https://github.com/fuma-nama/fumadocs/blob/2a1211e77ba1ef8f9435a1f1ec7919f5307b83ed/packages/ui/src/components/nav.tsx#L2C34-L2C44)

With a [dependency](https://github.com/fuma-nama/fumadocs/blob/2a1211e77ba1ef8f9435a1f1ec7919f5307b83ed/packages/ui/package.json#L107C5-L107C32) on a broken version of lucide-react

Am I missing something that would cause you not to get the same error?

**Comment by ahaubenstock** [comment] 2024-05-29 11:24
I tested it with those versions and am getting the same error. I am attaching a zip with a reproducible example. All I did was run `pnpm create fumadocs-app` to create it.
[svg-error.zip](https://github.com/fuma-nama/fumadocs/files/15483494/svg-error.zip)

**Comment by fuma-nama** [comment] 2024-05-29 12:23
The example doesn't include a lock file, running it doesn't give me any SVG hydration warnings.
![image](https://github.com/fuma-nama/fumadocs/assets/76240755/f62f79bc-94a3-4630-a6f1-aa9f5f5e3580)

**Comment by ahaubenstock** [comment] 2024-05-31 08:55
@fuma-nama You're right. After upgrading the lucide-react dependency to latest, the error disappears. I did not open this issue, but I agree that it's not an issue with this repository.

**Comment by fuma-nama** [comment] 2024-06-14 13:22
I'll closing this issue for now, for those who encountered this problem, make sure the `lucide-react` you've installed is the latest version!

**Closed by fuma-nama** 2024-06-14 13:22 UTC
Labels: bug
