### ISSUE TITLE
NormalizeError: Requested and resolved page mismatch: Next

### ISSUE THREAD

**Issue by Siumauricio** [fuma-nama/fumadocs#462] opened 2024-06-14 07:10 UTC
### To Reproduce

1. Clone this [Repository I18N from the examples](https://github.com/fuma-nama/fumadocs/tree/dev/examples/i18n) or use [Repository from dokploy-docs](https://github.com/Dokploy/docs/tree/feat/fumadocs)
2. pnpm install
3. pnpm run build (Error)

### Current vs. Expected behavior

**Current**:

mauricio ~/Desktop/test/i18n  $ pnpm run build

> example-i18n@0.0.0 build /Users/mauricio/Desktop/test/i18n
> next build

  ▲ Next.js 14.2.4

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    

> Build error occurred
NormalizeError: Requested and resolved page mismatch: //test /test
    at normalizePagePath (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/shared/lib/page-path/normalize-page-path.js:20:19)
    at /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/index.js:385:146
    at Array.map (<anonymous>)
    at exportAppImpl (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/index.js:385:47)
    at async /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/index.js:623:16
    at async Span.traceAsyncFn (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/index.js:1696:42
    at async Span.traceAsyncFn (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/index.js:1543:17
    at async Span.traceAsyncFn (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
 ELIFECYCLE  Command failed with exit code 1.
mauricio ~/Desktop/test/i18n  $ 

Expected:
Build sucesfully

### Provide environment information

```bash
mauricio ~/Desktop/test/i18n  $ npx next info                                

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: 8.15.4
Relevant Packages:
  next: 14.2.4 // Latest available version is detected (14.2.4).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Examples

### Additional context

I tested on a different versions of nextjs since this seems related to nextjs itself however i try to downgrade a few versions but the same issue, I tried to build both repositories from the example and from the dokploy docs and the same error.

Also from the example I18N i tried to delete the test.mdx and only left the index.mdx and index.cn.mdx and it throw the following error:

Error: The provided export path '/' doesn't match the '/[lang]/[[...slug]]' page.
Read more: https://nextjs.org/docs/messages/export-path-mismatch
    at getParams (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/helpers/get-params.js:27:15)
    at exportPageImpl (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/worker.js:91:47)
    at /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/worker.js:236:110
    at turborepoTraceAccess (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/turborepo-access-trace/helpers.js:36:51)
    at /Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/worker.js:236:105
    at Span.traceAsyncFn (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:26)
    at Object.exportPage (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/export/worker.js:236:41)
    at execFunction (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2764)
    at execHelper (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2422)
    at execMethod (/Users/mauricio/Desktop/test/i18n/node_modules/.pnpm/next@14.2.4_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2510)
 ✓ Generating static pages (7/7)

**Comment by fuma-nama** [comment] 2024-06-14 07:53
I confirmed the bug is happening on the demo.
The error is caused by the `getLanguages()` function. It sets an empty string to the `language` property for the default language, which is not a valid value.
Will be fixed soon

**Comment by fuma-nama** [comment] 2024-06-14 08:10
Fixed!

**Closed by fuma-nama** 2024-06-14 08:10 UTC
Labels: bug

**Comment by Siumauricio** [comment] 2024-06-14 17:31
Thank you!
