### ISSUE TITLE
Use fumadocs together with tailwind website

### ISSUE THREAD

**Issue by ccfai8** [fuma-nama/fumadocs#434] opened 2024-06-08 08:58 UTC
### What problem will this feature address?

im using daisy ui for theme, tremor and tailwind for global css style and custom style.

i found that if i add fumadocs to next.config.mjs and visit https://website.com/docs, nextjs hydration error shows up and it seems that css conflicts happen. I guess this is because tailwind is in conflict with import 'fumadocs-ui/style.css';.

even i remove it, hydration error happens but error dont occur for nextra theme.

### Describe the solution you'd like

 on next.config.mjs, for nextra, we have the following:

```
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./nextra-theme.config.tsx",
});

export default withNextra(config);

```

is it possible to have theme: "fumadocs-ui-style", instead so that it will override global.css?

### Describe alternatives you've considered

Thanks so much for building such a beautiful documentation! I really love it but it seems that i cannot use mutiple style for my site but will need to create a new app. Thanks.

**Comment by fuma-nama** [comment] 2024-06-08 09:10
The docs has a specific page for using Tailwind CSS with Fumadocs, you should read it first.

And please provide the hydration error and logs, it lacks of necessary information to debug.

**Comment by ccfai8** [comment] 2024-06-08 09:48
> The docs has a specific page for using Tailwind CSS with Fumadocs, you should read it first.
> 
> And please provide the hydration error and logs, it lacks of necessary information to debug.

Thanks fuma. i actually want to use `import 'fumadocs-ui/style.css';`

but if i apply it to my layout.tsx.
```
import { RootProvider } from 'fumadocs-ui/provider';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';
import 'fumadocs-ui/style.css';

const inter = Inter({
  subsets: ['latin'],
});

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}

```

error occurs
<img width="980" alt="Screenshot 2024-06-08 at 2 48 21 AM" src="https://github.com/fuma-nama/fumadocs/assets/18694471/d7da9022-0396-4ac2-9554-6cba4eb4c61e">

**Comment by ccfai8** [comment] 2024-06-08 09:50
here is my tailwind setting. since i want to use` import 'fumadocs-ui/style.css';`, i didnt change my existing tailwind code. even i change it to the template code, i still get hydration error.
```
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./node_modules/@tremor/**/*.{js,ts,jsx,tsx}",
  ],
```

**Comment by ccfai8** [comment] 2024-06-08 09:54
<img width="1612" alt="Screenshot 2024-06-08 at 2 53 54 AM" src="https://github.com/fuma-nama/fumadocs/assets/18694471/f5683add-0cf1-4078-8891-baf8f065b31b">
after i refresh, it becomes back to the official theme.

**Comment by fuma-nama** [comment] 2024-06-08 10:02
As told, follow https://fumadocs.vercel.app/docs/ui/theme#usage to setup the tailwind css plugin rather than using the prebuilt stylesheet.

**Comment by fuma-nama** [comment] 2024-06-08 10:06
Nextra uses Page Router which has a different logic in handling css file imports. For best compatibility, you are supposed to use the tailwind css plugin. All instructions are written on docs.

**Comment by ccfai8** [comment] 2024-06-08 10:44
> As told, follow https://fumadocs.vercel.app/docs/ui/theme#usage to setup the tailwind css plugin rather than using the prebuilt stylesheet.

Thanks fuma for your reply! I really appreciate it. I did follow the doc. but hydration error still occurs. I copied the exact same code and also tried my own one as below.
```

import { type Config } from "tailwindcss";
import plugin from 'tailwindcss/plugin';
import { createPreset } from 'fumadocs-ui/tailwind-plugin';

export default {
  presets: [
    createPreset({
      preset: 'ocean',
    }),
  ],

  content: [
    "./src/**/*.{js,ts,jsx,tsx,md,mdx}",
    "./node_modules/@tremor/**/*.{js,ts,jsx,tsx}",
    "./nextra-theme.config.tsx",
    './content/**/*.{md,mdx}',
    './mdx-components.{ts,tsx}',
    './node_modules/fumadocs-ui/dist/**/*.js',

  ],
```
<img width="1462" alt="Screenshot 2024-06-08 at 3 41 05 AM" src="https://github.com/fuma-nama/fumadocs/assets/18694471/1c770e12-7d5f-4051-929b-863abcac2836">
<img width="1392" alt="Screenshot 2024-06-08 at 3 41 11 AM" src="https://github.com/fuma-nama/fumadocs/assets/18694471/f0f255de-53b4-4634-9fc8-52c3f92046c1">

so every time i visit the doc index.mdx, it is using my tailwind set up with the hydration error in the above comments. what i am proposing here is to provide the option to use the default pre-built css style (fumadocs-ui/style.css). something like below
```
import nextra from "nextra";

const withNextra = nextra({
  theme: "nextra-theme-docs",
  themeConfig: "./nextra-theme.config.tsx",
});

export default withNextra(config);

```

im totally new to coding so i might sound stupid to you. sorry if im proposing something totally wrong!

**Comment by fuma-nama** [comment] 2024-06-08 11:41
I think the hydration problem is caused by your code but your question lacks of sufficient information (e.g. logs, error stack trace and reproducible example). You may open an issue following the bug report template, or edit your original issue to include these information.

**Comment by fuma-nama** [comment] 2024-06-08 11:44
Especially the noscript tag isn't attached by fumadocs, I'm sure it's the problem of other dependencies and you might need to check if the dependencies you are using are compatible with App Router.

**Comment by ccfai8** [comment] 2024-06-09 02:44
> noscript

Thanks fuma~

I checked again with bot and it seems that it is because of the html and body tag?
Missing required html tags
The following tags are missing in the Root Layout: <html>, <body>. Read more at https://nextjs.org/docs/messages/missing-root-layout-tags

Edit
I apologize for the confusion in my previous responses. You're absolutely right that Next.js requires the <html> and <body> tags to be present in the root layout when using the app directory.

Based on the error message you provided, it seems that the fumadocs-ui package is not fully compatible with Next.js's app directory and its requirement for the <html> and <body> tags to be included in the root layout.

To resolve this issue, you have a few options:

Modify the fumadocs-ui package:
If you have access to the source code of the fumadocs-ui package, you can try modifying it to work with Next.js's app directory and ensure that it doesn't clash with the required <html> and <body> tags.
This may involve updating the RootProvider and DocsLayout components to accommodate the Next.js requirements.
Use a different documentation UI library:
Consider using an alternative documentation UI library that is fully compatible with Next.js and its app directory.
Some popular options include Docusaurus, GitBook, or building a custom documentation layout using Next.js components.
Use a different directory structure:
If you want to continue using the fumadocs-ui package without modifications, you can move your documentation pages outside of the app directory and into a separate directory, such as pages/docs.
This way, you can leverage Next.js's pages directory and its file-based routing system, which doesn't have the same requirements for the <html> and <body> tags in the root layout.

**Comment by ccfai8** [comment] 2024-06-09 12:13
> Especially the noscript tag isn't attached by fumadocs, I'm sure it's the problem of other dependencies and you might need to check if the dependencies you are using are compatible with App Router.

Thanks again fuma! what im proposing here is to allow using custom theme. something like below.
```
const withNextra = require('nextra')({
  theme: './theme.tsx',
})
 
module.exports = withNextra({
  // Other Next.js configurations
  ...
})
```

**Comment by fuma-nama** [comment] 2024-06-09 16:07
In fumadocs, we do it differently, you can read the philosophy from our comparison page. 

For custom themes, you can change the options of our Tailwind CSS plugin, style it with CSS, or pass props to the corresponding components directly.

See https://fumadocs-dev.vercel.app/docs/ui#customise

**Comment by fuma-nama** [comment] 2024-06-14 04:00
I'm closing this for now, you can open a bug report if the problem persists. Thanks!

**Closed by fuma-nama** 2024-06-14 04:00 UTC
Labels: enhancement
