### ISSUE TITLE
feat: collision support for twoslash blocks

### ISSUE THREAD

**Issue by juliusmarminge** [fuma-nama/fumadocs#233] opened 2024-01-31 14:11 UTC
**Is your feature request related to a problem? Please describe.**

Would be nice for shiki to have some form of collision avoiding on the shiki blocks. For example, this isn't the best since it covers most of the row underneath it:

![CleanShot 2024-01-31 at 15 07 13](https://github.com/fuma-nama/fumadocs/assets/51714798/b2249253-61d0-4264-b050-9d394e66d098)

**Describe the solution you'd like**

The docusaurus twoslash plugin does this fairly well:

![CleanShot 2024-01-31 at 15 09 51](https://github.com/fuma-nama/fumadocs/assets/51714798/750de180-8fd4-4100-8415-f8542b1c319d)

> Link: https://trpc.io/docs/quickstart#2-querying--mutating
> Source: https://github.com/trpc/trpc/blob/next/www/docs/main/quickstart.mdx#L473-L477

**Describe alternatives you've considered**

-

**Comment by fuma-nama** [comment] 2024-02-01 09:23
duplicate of #234

**Closed by fuma-nama** 2024-02-01 09:23 UTC
