### ISSUE TITLE
OpenAPI generation fails with `nullable` properties

### ISSUE THREAD

**Issue by perkinsjr** [fuma-nama/fumadocs#433] opened 2024-06-07 15:51 UTC
### To Reproduce

1. Use `https://api.unkey.dev/openapi.json` which is a 3.0 spec that contains 'nullable' properties.
2. Attempt to use OpenAPI generation 

### Current vs. Expected behavior

Current behavior produces the following error: 

```
file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:294
  throw new Error(`Cannot detect object type: ${JSON.stringify(schema)}`);
        ^

Error: Cannot detect object type: {"nullable":false}
    at getSchemaType (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:294:9)
    at getSchemaType (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:280:15)
    at schemaElement (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:264:13)
    at schemaElement (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:215:11)
    at schemaElement (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:252:11)
    at file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:225:9
    at Array.forEach (<anonymous>)
    at schemaElement (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:223:38)
    at renderOperation (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:314:7)
    at generate (file:///Users/james/Development/fuma-docs-template/node_modules/.pnpm/fumadocs-openapi@2.0.2/node_modules/fumadocs-openapi/dist/index.js:442:20)

Node.js v22.1.0
```

Expected behavior is that the generator would successfully render content, this currently works in Mintlify as expected.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:59 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8122
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 22.1.0
  npm: 10.7.0
  Yarn: N/A
  pnpm: 9.0.6
Relevant Packages:
  next: 14.2.3 // Latest available version is detected (14.2.3).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Integrations (e.g Contentlayer, OpenAPI, Typescript DocsGen)

**Comment by fuma-nama** [comment] 2024-06-08 05:33
It is caused by a `{ "nullable": true }` property with no type specified, will be fixed in v12

**Comment by fuma-nama** [comment] 2024-06-09 08:03
Fixed since v12

**Closed by fuma-nama** 2024-06-09 08:03 UTC
Labels: bug
